### ISSUE TITLE
AttributeError in python 3.3

### ISSUE THREAD

**Issue by migueldvb** [aliles/filemagic#10]
When I use `magi.Magic` in a `with` context statement in python 3.3 I get the following error:

`AttributeError: __exit__`

This problem is not present in earlier versions of python.

**Comment by aliles** [comment]
Hi, thank you for reporting this issue. Sounds like I've made a silly error.

Which previous version(s) of Python have you confirmed work on for you?

**Comment by migueldvb** [comment]
It used to work well in python 2.6 and 2.7.

**Comment by tankbusta** [comment]
This isn't a Python 3.3 problem as the same error occurs on the latest 2.7.X builds. (even the [test cases](https://github.com/aliles/filemagic/blob/master/tests/test_magic.py#L28) properly instantiate magic.Magic)

This should be merged :+1:
